/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/assets/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List assets (paginated) or export them as CSV
         * @description List assets visible to ``current_user``.
         *
         *     With ``export=csv`` an unpaginated ``text/csv`` stream is returned;
         *     otherwise a paginated :class:`AssetListResponse` is returned.
         */
        get: operations["list_assets_api_v1_assets__get"];
        put?: never;
        /**
         * Create a new asset
         * @description Create a new asset within a tenant.
         *
         *     Tenant rules (D-007):
         *
         *     * Non-superadmin: ``payload.tenant_id`` MUST equal
         *       ``current_user.tenant_id``; otherwise 422 ``tenant_id mismatch``.
         *     * Superadmin: ``payload.tenant_id`` MUST be present and must resolve
         *       to an existing tenant; otherwise 422.
         */
        post: operations["create_asset_api_v1_assets__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/assets/{asset_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get an asset by id
         * @description Return the asset, or 404 if it doesn't exist in the visible scope.
         */
        get: operations["get_asset_api_v1_assets__asset_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete an asset
         * @description Delete an asset. 404 if it doesn't exist in the visible scope.
         */
        delete: operations["delete_asset_api_v1_assets__asset_id__delete"];
        options?: never;
        head?: never;
        /**
         * Update an asset
         * @description Apply a partial update to an asset.
         */
        patch: operations["update_asset_api_v1_assets__asset_id__patch"];
        trace?: never;
    };
    "/api/v1/auth/change-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Change Password */
        post: operations["change_password_api_v1_auth_change_password_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_api_v1_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refresh */
        post: operations["refresh_api_v1_auth_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/dashboard/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Summary
         * @description Return metrics for the caller's tenant or an explicit superadmin target.
         */
        get: operations["get_summary_api_v1_dashboard_summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reports/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List reports (paginated), optionally filtered
         * @description List reports visible to ``current_user``, newest first.
         *
         *     With ``asset_id`` the SAME asset resolution as POST runs first, so an
         *     invisible or missing asset is 404 rather than an empty page.
         */
        get: operations["list_reports_api_v1_reports__get"];
        put?: never;
        /**
         * Create a new report
         * @description Create a new report for a visible asset of the effective target tenant.
         *
         *     The asset must resolve as ``Asset.id == asset_id`` AND
         *     ``Asset.tenant_id == effective tenant`` (even for a superadmin — this
         *     validates the report/asset coherence, not global visibility). A miss is
         *     404 ``report asset not found`` and nothing is persisted.
         */
        post: operations["create_report_api_v1_reports__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reports/{report_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a report by id
         * @description Return the report, or 404 if it doesn't exist in the visible scope.
         */
        get: operations["get_report_api_v1_reports__report_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete a report
         * @description Delete a report. 404 if it doesn't exist in the visible scope.
         */
        delete: operations["delete_report_api_v1_reports__report_id__delete"];
        options?: never;
        head?: never;
        /**
         * Update a report
         * @description Apply a partial update to a report.
         */
        patch: operations["update_report_api_v1_reports__report_id__patch"];
        trace?: never;
    };
    "/api/v1/scans/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List scans (paginated), optionally filtered by asset
         * @description List scans visible to ``current_user``, newest first.
         *
         *     With ``asset_id`` the SAME asset resolution as POST runs first, so an
         *     invisible or missing asset is 404 rather than an empty page.
         */
        get: operations["list_scans_api_v1_scans__get"];
        put?: never;
        /**
         * Create a new scan definition
         * @description Create a new scan for a visible asset of the effective target tenant.
         *
         *     The asset must resolve as ``Asset.id == asset_id`` AND
         *     ``Asset.tenant_id == effective tenant`` (even for a superadmin — this
         *     validates the scan/asset coherence, not global visibility). A miss is
         *     404 ``scan asset not found`` and nothing is persisted.
         */
        post: operations["create_scan_api_v1_scans__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/scans/{scan_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a scan by id
         * @description Return the scan, or 404 if it doesn't exist in the visible scope.
         */
        get: operations["get_scan_api_v1_scans__scan_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete a scan
         * @description Delete a scan. 404 if it doesn't exist in the visible scope.
         */
        delete: operations["delete_scan_api_v1_scans__scan_id__delete"];
        options?: never;
        head?: never;
        /**
         * Update a scan
         * @description Apply a partial update to a scan.
         */
        patch: operations["update_scan_api_v1_scans__scan_id__patch"];
        trace?: never;
    };
    "/api/v1/scans/{scan_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Cancel a pending or running scan
         * @description Stop an open scan, regardless of the execution kill switch.
         *
         *     Terminal scans return 409; missing or invisible scans return 404.
         *     The worker observes cancellation and terminates the running subprocess.
         */
        post: operations["cancel_scan_api_v1_scans__scan_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/scans/{scan_id}/enrichment": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Request Scan Enrichment */
        post: operations["request_scan_enrichment_api_v1_scans__scan_id__enrichment_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/scans/{scan_id}/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Dispatch a pending scan for asynchronous execution
         * @description Commit the dispatch as the source of truth, then ring a best-effort bell.
         *
         *     Broker delivery is only a hint to the worker: failure still returns 202
         *     and preserves the committed dispatch. The periodic pump recovers a lost
         *     bell by waking the worker to claim pending work from PostgreSQL.
         */
        post: operations["run_scan_api_v1_scans__scan_id__run_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tenants/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Listar todos los tenants
         * @description Lista paginada de tenants
         */
        get: operations["list_tenants_api_v1_tenants__get"];
        put?: never;
        /**
         * Crear nuevo tenant
         * @description Crea una nueva organizacion- Solo superadmin
         */
        post: operations["create_tenant_api_v1_tenants__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tenants/{tenant_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Obtener tenant por id
         * @description Obtiene un tenant por id.
         *
         *     The cross-tenant pre-check fires inside the Depends (R01 tenants,
         *     RK-6 unified 403 contract). Cross-tenant access returns 403 with
         *     a `cross_tenant_access_blocked` log line. The Depends handles both
         *     the pre-check and the 404-on-missing-row case.
         */
        get: operations["get_tenant_api_v1_tenants__tenant_id__get"];
        put?: never;
        post?: never;
        /**
         * Desactivar tenant
         * @description Desactiva un tenant, sus usuarios, y revoca todas las sesiones
         */
        delete: operations["deactivate_tenant_api_v1_tenants__tenant_id__delete"];
        options?: never;
        head?: never;
        /**
         * Actualizar tenant
         * @description Actualiza campos de un tenant
         */
        patch: operations["update_tenant_api_v1_tenants__tenant_id__patch"];
        trace?: never;
    };
    "/api/v1/users/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Users
         * @description Lista de usuarios
         */
        get: operations["list_users_api_v1_users__get"];
        put?: never;
        /**
         * Create User
         * @description Crea un nuevo usuario
         */
        post: operations["create_user_api_v1_users__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Me
         * @description Devuelve el perfil del usuario autenticado
         */
        get: operations["get_me_api_v1_users_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get User
         * @description Obtiene un usuario por ID.
         *
         *     The cross-tenant pre-check fires inside the Depends (R01, R04, R05).
         *     A same-tenant admin or the user themselves can read; cross-tenant
         *     access returns 403 with a `cross_tenant_access_blocked` log line.
         */
        get: operations["get_user_api_v1_users__user_id__get"];
        put?: never;
        post?: never;
        /**
         * Deactivate User
         * @description Desactiva un usuario y revoca todas sus sesiones.
         *
         *     The cross-tenant pre-check fires inside the Depends (R03, R04, R05).
         *     The in-router policy checks (self-deactivation 409, superadmin
         *     deactivation 403, admin-deactivates-admin 403) STAY HERE — they
         *     are policy rules, not tenant rules.
         */
        delete: operations["deactivate_user_api_v1_users__user_id__delete"];
        options?: never;
        head?: never;
        /**
         * Update User
         * @description Actualiza un usuario.
         *
         *     The cross-tenant pre-check fires inside the Depends (R02, R04, R05).
         *     The in-router policy checks (self-deactivation 409, role hierarchy
         *     403, admin-modifies-superadmin 403) STAY HERE — they are policy
         *     rules, not tenant rules.
         */
        patch: operations["update_user_api_v1_users__user_id__patch"];
        trace?: never;
    };
    "/api/v1/vulnerabilities/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List vulnerabilities (paginated), optionally filtered by scan
         * @description List vulnerabilities visible to ``current_user``, newest first.
         *
         *     With ``scan_id`` the SAME scan resolution as POST runs first, so an
         *     invisible or missing scan is 404 rather than an empty page.
         */
        get: operations["list_vulnerabilities_api_v1_vulnerabilities__get"];
        put?: never;
        /**
         * Create a new vulnerability
         * @description Create a new vulnerability for a visible scan of the effective target tenant.
         *
         *     The scan must resolve as ``Scan.id == scan_id`` AND
         *     ``Scan.tenant_id == effective tenant`` (even for a superadmin — this
         *     validates the vulnerability/scan coherence, not global visibility). A
         *     miss is 404 ``vulnerability scan not found`` and nothing is persisted.
         */
        post: operations["create_vulnerability_api_v1_vulnerabilities__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/vulnerabilities/{vulnerability_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a vulnerability by id
         * @description Return the vulnerability, or 404 if it doesn't exist in the visible scope.
         */
        get: operations["get_vulnerability_api_v1_vulnerabilities__vulnerability_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete a vulnerability
         * @description Delete a vulnerability. 404 if it doesn't exist in the visible scope.
         */
        delete: operations["delete_vulnerability_api_v1_vulnerabilities__vulnerability_id__delete"];
        options?: never;
        head?: never;
        /**
         * Update a vulnerability
         * @description Apply a partial update to a vulnerability.
         */
        patch: operations["update_vulnerability_api_v1_vulnerabilities__vulnerability_id__patch"];
        trace?: never;
    };
    "/api/v1/vulnerabilities/{vulnerability_id}/enrichment": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Enrichment */
        get: operations["get_enrichment_api_v1_vulnerabilities__vulnerability_id__enrichment_get"];
        put?: never;
        /** Request Enrichment */
        post: operations["request_enrichment_api_v1_vulnerabilities__vulnerability_id__enrichment_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/db/indexes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List invalid public-schema indexes (k8s probe target). */
        get: operations["db_index_health_health_db_indexes_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AssetResponse
         * @description The public Assets response.
         *
         *     Only six fields are exposed. The ``from_orm_instance`` helper performs
         *     the explicit ``asset_type`` → ``type`` mapping so the ORM column name
         *     never leaks (D-009).
         */
        AssetResponse: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Tenant Id
             * Format: uuid
             */
            tenant_id: string;
            /**
             * Type
             * @enum {string}
             */
            type: "ip" | "domain" | "hostname" | "web_app" | "subnet" | "cloud_resource";
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Value */
            value: string;
        };
        /**
         * AssetUpdate
         * @description Partial update payload.
         *
         *     Both fields are optional; the service combines the supplied values
         *     with the persisted state and validates the resulting pair. Unknown
         *     keys are rejected.
         */
        AssetUpdate: {
            /** Type */
            type?: ("ip" | "domain" | "hostname" | "web_app" | "subnet" | "cloud_resource") | null;
            /** Value */
            value?: string | null;
        };
        /** ChangePasswordRequest */
        ChangePasswordRequest: {
            /** Current Password */
            current_password: string;
            /** New Password */
            new_password: string;
        };
        /** CloudResourceAssetCreate */
        CloudResourceAssetCreate: {
            /**
             * Tenant Id
             * Format: uuid
             */
            tenant_id: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "cloud_resource";
            /** Value */
            value: string;
        };
        /**
         * CoverageMetric
         * @description Recent scan coverage of active assets.
         */
        CoverageMetric: {
            /** Covered */
            covered: number;
            /**
             * Ratio
             * @description 0..1 fraction rounded to 4 decimals; None when total is 0 (no data, not 0 %).
             */
            ratio: number | null;
            /**
             * Since
             * Format: date-time
             */
            since: string;
            /** Total */
            total: number;
        };
        /**
         * DashboardSummary
         * @description Tenant-scoped dashboard metrics at the database clock time.
         */
        DashboardSummary: {
            /** Assets Monitored */
            assets_monitored: number;
            coverage_24h: components["schemas"]["CoverageMetric"];
            /**
             * Generated At
             * Format: date-time
             */
            generated_at: string;
            open_by_severity: components["schemas"]["SeverityCounts"];
            scan_success_30d: components["schemas"]["ScanSuccessMetric"];
            /**
             * Tenant Id
             * Format: uuid
             */
            tenant_id: string;
            /** Trend 30D */
            trend_30d: components["schemas"]["TrendDay"][];
        };
        /** DiscoveryConfig */
        DiscoveryConfig: {
            /** Host Discovery */
            host_discovery: boolean;
        };
        /** DiscoveryScanCreate */
        DiscoveryScanCreate: {
            /**
             * Asset Id
             * Format: uuid
             */
            asset_id: string;
            config: components["schemas"]["DiscoveryConfig"];
            /** Name */
            name: string;
            /**
             * Tenant Id
             * Format: uuid
             */
            tenant_id: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "discovery";
        };
        /** DomainAssetCreate */
        DomainAssetCreate: {
            /**
             * Tenant Id
             * Format: uuid
             */
            tenant_id: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "domain";
            /** Value */
            value: string;
        };
        /** EnrichmentItemRead */
        EnrichmentItemRead: {
            /**
             * Attempts
             * @default 0
             */
            attempts: number;
            /** Content */
            content?: string | null;
            /** Error */
            error?: string | null;
            /** Function */
            function: string;
            /** Model */
            model?: string | null;
            /** Prompt Version */
            prompt_version?: string | null;
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "failed" | "pending" | "missing";
            /** Updated At */
            updated_at?: string | null;
        };
        /** EnrichmentQueued */
        EnrichmentQueued: {
            /** Queued */
            queued: number;
        };
        /** FullConfig */
        FullConfig: {
            /** Checks */
            checks: string[];
            /** Host Discovery */
            host_discovery: boolean;
            /** Paths */
            paths: string[];
        };
        /** FullScanCreate */
        FullScanCreate: {
            /**
             * Asset Id
             * Format: uuid
             */
            asset_id: string;
            config: components["schemas"]["FullConfig"];
            /** Name */
            name: string;
            /**
             * Tenant Id
             * Format: uuid
             */
            tenant_id: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "full";
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HostnameAssetCreate */
        HostnameAssetCreate: {
            /**
             * Tenant Id
             * Format: uuid
             */
            tenant_id: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "hostname";
            /** Value */
            value: string;
        };
        /** IpAssetCreate */
        IpAssetCreate: {
            /**
             * Tenant Id
             * Format: uuid
             */
            tenant_id: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "ip";
            /** Value */
            value: string;
        };
        /** LoginRequest */
        LoginRequest: {
            /** Email */
            email: string;
            /** Password */
            password: string;
        };
        /**
         * ReportCreate
         * @description Create payload.
         *
         *     ``status`` and ``generated_at`` are deliberately absent: the server forces
         *     ``status="pending"`` and ``generated_at=None`` regardless of client input.
         */
        ReportCreate: {
            /**
             * Asset Id
             * Format: uuid
             */
            asset_id: string;
            /** Name */
            name: string;
            /** Report Metadata */
            report_metadata?: Record<string, never> | null;
            /**
             * Report Type
             * @enum {string}
             */
            report_type: "vulnerability" | "executive" | "technical" | "compliance";
            /** Summary */
            summary?: string | null;
            /**
             * Tenant Id
             * Format: uuid
             */
            tenant_id: string;
        };
        /**
         * ReportListResponse
         * @description Paginated list response: items plus the page metadata.
         */
        ReportListResponse: {
            /** Items */
            items: components["schemas"]["ReportResponse"][];
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /** Total */
            total: number;
        };
        /**
         * ReportResponse
         * @description The public Reports response.
         */
        ReportResponse: {
            /**
             * Asset Id
             * Format: uuid
             */
            asset_id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Generated At */
            generated_at: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Report Metadata */
            report_metadata: Record<string, never> | null;
            /**
             * Report Type
             * @enum {string}
             */
            report_type: "vulnerability" | "executive" | "technical" | "compliance";
            /**
             * Status
             * @enum {string}
             */
            status: "pending" | "generating" | "completed" | "failed";
            /** Summary */
            summary: string | null;
            /**
             * Tenant Id
             * Format: uuid
             */
            tenant_id: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * ReportUpdate
         * @description Partial update payload.
         *
         *     Only ``name``, ``status``, ``summary``, ``report_metadata`` and
         *     ``generated_at`` are accepted. ``tenant_id``, ``asset_id`` and
         *     ``report_type`` identify the report and never change once recorded.
         *     ``name`` and ``status`` are NOT NULL columns, so an explicit ``null`` is
         *     rejected with 422 instead of reaching the database.
         */
        ReportUpdate: {
            /** Generated At */
            generated_at?: string | null;
            /** Name */
            name?: string | null;
            /** Report Metadata */
            report_metadata?: Record<string, never> | null;
            /** Status */
            status?: ("pending" | "generating" | "completed" | "failed") | null;
            /** Summary */
            summary?: string | null;
        };
        /**
         * RoleEnum
         * @enum {string}
         */
        RoleEnum: "viewer" | "analyst" | "ingestor" | "admin" | "superadmin";
        /** ScanEnrichmentQueued */
        ScanEnrichmentQueued: {
            /** Queued */
            queued: number;
            /** Total */
            total: number;
        };
        /** ScanLimits */
        ScanLimits: {
            /**
             * Concurrent Max
             * @default 1
             */
            concurrent_max: number;
            /**
             * Daily Max
             * @default 5
             */
            daily_max: number;
        };
        /**
         * ScanListResponse
         * @description Paginated list response: items plus the page metadata.
         */
        ScanListResponse: {
            /** Items */
            items: components["schemas"]["ScanResponse"][];
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /** Total */
            total: number;
        };
        /**
         * ScanResponse
         * @description The public Scans response.
         *
         *     Exactly eleven fields. ``from_orm_instance`` performs the explicit
         *     ``scan_type`` -> ``type`` mapping so the column name never reaches the wire
         *     and no other ORM attribute is serialised implicitly.
         */
        ScanResponse: {
            /**
             * Asset Id
             * Format: uuid
             */
            asset_id: string;
            /** Completed At */
            completed_at: string | null;
            /** Config */
            config: Record<string, never> | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Started At */
            started_at: string | null;
            /**
             * Status
             * @enum {string}
             */
            status: "pending" | "running" | "completed" | "failed" | "cancelled";
            /**
             * Tenant Id
             * Format: uuid
             */
            tenant_id: string;
            /**
             * Type
             * @enum {string}
             */
            type: "discovery" | "vulnerability" | "web" | "full";
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * ScanSuccessMetric
         * @description Completed and failed scans within the rolling window.
         */
        ScanSuccessMetric: {
            /** Completed */
            completed: number;
            /** Failed */
            failed: number;
            /**
             * Ratio
             * @description 0..1 fraction rounded to 4 decimals; None when completed + failed is 0 (no data, not 0 %).
             */
            ratio: number | null;
            /**
             * Since
             * Format: date-time
             */
            since: string;
        };
        /**
         * ScanUpdate
         * @description Partial update payload.
         *
         *     Only the mutable public fields are accepted. ``tenant_id``, ``asset_id``,
         *     ``status``, ``started_at`` and ``completed_at`` cannot appear here: the
         *     identity of a scan never changes, and its lifecycle is owned by the
         *     execution slices, never by an HTTP client.
         */
        ScanUpdate: {
            /** Config */
            config?: Record<string, never> | null;
            /** Name */
            name?: string | null;
            /** Type */
            type?: ("discovery" | "vulnerability" | "web" | "full") | null;
        };
        /**
         * SeverityCounts
         * @description Open findings by severity, including zero counts.
         */
        SeverityCounts: {
            /**
             * Critical
             * @default 0
             */
            critical: number;
            /**
             * High
             * @default 0
             */
            high: number;
            /**
             * Info
             * @default 0
             */
            info: number;
            /**
             * Low
             * @default 0
             */
            low: number;
            /**
             * Medium
             * @default 0
             */
            medium: number;
        };
        /** SubnetAssetCreate */
        SubnetAssetCreate: {
            /**
             * Tenant Id
             * Format: uuid
             */
            tenant_id: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "subnet";
            /** Value */
            value: string;
        };
        /** TenantCreate */
        TenantCreate: {
            /**
             * Max Assets
             * @default 10
             */
            max_assets: number;
            /** Name */
            name: string;
            /**
             * Plan
             * @default free
             * @enum {string}
             */
            plan: "free" | "starter" | "pro" | "enterprise";
            /**
             * @default {
             *       "baseline_reset_requested": false,
             *       "log_buffer_max": 500,
             *       "scan_limits": {
             *         "concurrent_max": 1,
             *         "daily_max": 5
             *       },
             *       "scan_schedule": "0 2 * * *",
             *       "severity_threshold": "medium",
             *       "timezone": "Europe/Madrid"
             *     }
             */
            settings: components["schemas"]["TenantSettings"];
            /** Slug */
            slug?: string | null;
        };
        /** TenantResponse */
        TenantResponse: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Is Active */
            is_active: boolean;
            /** Max Assets */
            max_assets: number;
            /** Name */
            name: string;
            /** Plan */
            plan: string;
            settings: components["schemas"]["TenantSettings"];
            /** Slug */
            slug: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** TenantSettings */
        TenantSettings: {
            /**
             * Baseline Reset Requested
             * @default false
             */
            baseline_reset_requested: boolean;
            /**
             * Log Buffer Max
             * @default 500
             */
            log_buffer_max: number;
            /** Notification Email */
            notification_email?: string | null;
            /**
             * @default {
             *       "concurrent_max": 1,
             *       "daily_max": 5
             *     }
             */
            scan_limits: components["schemas"]["ScanLimits"];
            /**
             * Scan Schedule
             * @default 0 2 * * *
             */
            scan_schedule: string;
            /**
             * Severity Threshold
             * @default medium
             * @enum {string}
             */
            severity_threshold: "critical" | "high" | "medium" | "low";
            /**
             * Timezone
             * @default Europe/Madrid
             */
            timezone: string;
        };
        /** TenantUpdate */
        TenantUpdate: {
            /** Is Active */
            is_active?: boolean | null;
            /** Max Assets */
            max_assets?: number | null;
            /** Name */
            name?: string | null;
            /** Plan */
            plan?: ("free" | "starter" | "pro" | "enterprise") | null;
            settings?: components["schemas"]["TenantSettings"] | null;
        };
        /** TokenResponse */
        TokenResponse: {
            /** Access Token */
            access_token: string;
            /** Expires In */
            expires_in: number;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
        };
        /**
         * TrendDay
         * @description Findings opened and closed on one UTC calendar day.
         */
        TrendDay: {
            /** Closed */
            closed: number;
            /**
             * Day
             * Format: date
             */
            day: string;
            /** Opened */
            opened: number;
        };
        /** UserCreate */
        UserCreate: {
            /**
             * Email
             * @description Email unico del usuario
             */
            email: string;
            /** Full Name */
            full_name: string;
            /** Password */
            password: string;
            /** @description Rol del usuario */
            role: components["schemas"]["RoleEnum"];
            /**
             * Tenant Id
             * @description Tenant requerido para creación pública
             */
            tenant_id: string | null;
        };
        /** UserResponse */
        UserResponse: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Email */
            email: string;
            /** Full Name */
            full_name: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Is Active */
            is_active: boolean;
            /** Is Superadmin */
            is_superadmin: boolean;
            role: components["schemas"]["RoleEnum"];
            /** Tenant Id */
            tenant_id: string | null;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** UserUpdate */
        UserUpdate: {
            /** Email */
            email?: string | null;
            /** Full Name */
            full_name?: string | null;
            /** Is Active */
            is_active?: boolean | null;
            role?: components["schemas"]["RoleEnum"] | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** VulnerabilityConfig */
        VulnerabilityConfig: {
            /** Checks */
            checks: string[];
        };
        /**
         * VulnerabilityCreate
         * @description Create payload.
         *
         *     ``status`` is deliberately absent: the server forces it to ``"open"``
         *     regardless of client input, matching the Scans pattern of owning the
         *     lifecycle server-side.
         */
        VulnerabilityCreate: {
            /** Cve Id */
            cve_id?: string | null;
            /** Cvss Score */
            cvss_score?: number | null;
            /** Description */
            description?: string | null;
            /**
             * Scan Id
             * Format: uuid
             */
            scan_id: string;
            /**
             * Severity
             * @enum {string}
             */
            severity: "critical" | "high" | "medium" | "low" | "info";
            /**
             * Tenant Id
             * Format: uuid
             */
            tenant_id: string;
            /** Title */
            title: string;
            /** Vulnerability Metadata */
            vulnerability_metadata?: Record<string, never> | null;
        };
        /** VulnerabilityEnrichmentRead */
        VulnerabilityEnrichmentRead: {
            /** Items */
            items: components["schemas"]["EnrichmentItemRead"][];
            /** Level */
            level: string;
            /**
             * Vulnerability Id
             * Format: uuid
             */
            vulnerability_id: string;
        };
        /**
         * VulnerabilityListResponse
         * @description Paginated list response: items plus the page metadata.
         */
        VulnerabilityListResponse: {
            /** Items */
            items: components["schemas"]["VulnerabilityResponse"][];
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /** Total */
            total: number;
        };
        /**
         * VulnerabilityResponse
         * @description The public Vulnerabilities response.
         */
        VulnerabilityResponse: {
            /** Closed At */
            closed_at: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Cve Id */
            cve_id: string | null;
            /** Cvss Score */
            cvss_score: number | null;
            /** Description */
            description: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Scan Id
             * Format: uuid
             */
            scan_id: string;
            /**
             * Severity
             * @enum {string}
             */
            severity: "critical" | "high" | "medium" | "low" | "info";
            /**
             * Status
             * @enum {string}
             */
            status: "open" | "fixed" | "accepted_risk" | "false_positive";
            /**
             * Tenant Id
             * Format: uuid
             */
            tenant_id: string;
            /** Title */
            title: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Vulnerability Metadata */
            vulnerability_metadata: Record<string, never> | null;
        };
        /** VulnerabilityScanCreate */
        VulnerabilityScanCreate: {
            /**
             * Asset Id
             * Format: uuid
             */
            asset_id: string;
            config: components["schemas"]["VulnerabilityConfig"];
            /** Name */
            name: string;
            /**
             * Tenant Id
             * Format: uuid
             */
            tenant_id: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "vulnerability";
        };
        /**
         * VulnerabilityUpdate
         * @description Partial update payload.
         *
         *     Only ``status``, ``description``, ``cvss_score`` and
         *     ``vulnerability_metadata`` are accepted. ``title``, ``scan_id``,
         *     ``tenant_id``, ``severity`` and ``cve_id`` cannot appear here: they
         *     identify the finding and where it came from, and never change once
         *     recorded — matching Scans' pattern of keeping identity fields out of
         *     PATCH.
         */
        VulnerabilityUpdate: {
            /** Cvss Score */
            cvss_score?: number | null;
            /** Description */
            description?: string | null;
            /** Status */
            status?: ("open" | "fixed" | "accepted_risk" | "false_positive") | null;
            /** Vulnerability Metadata */
            vulnerability_metadata?: Record<string, never> | null;
        };
        /** WebAppAssetCreate */
        WebAppAssetCreate: {
            /**
             * Tenant Id
             * Format: uuid
             */
            tenant_id: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "web_app";
            /** Value */
            value: string;
        };
        /** WebConfig */
        WebConfig: {
            /** Paths */
            paths: string[];
        };
        /** WebScanCreate */
        WebScanCreate: {
            /**
             * Asset Id
             * Format: uuid
             */
            asset_id: string;
            config: components["schemas"]["WebConfig"];
            /** Name */
            name: string;
            /**
             * Tenant Id
             * Format: uuid
             */
            tenant_id: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "web";
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_assets_api_v1_assets__get: {
        parameters: {
            query?: {
                offset?: number;
                limit?: number;
                export?: "csv" | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_asset_api_v1_assets__post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IpAssetCreate"] | components["schemas"]["DomainAssetCreate"] | components["schemas"]["HostnameAssetCreate"] | components["schemas"]["WebAppAssetCreate"] | components["schemas"]["SubnetAssetCreate"] | components["schemas"]["CloudResourceAssetCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssetResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_asset_api_v1_assets__asset_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                asset_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssetResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_asset_api_v1_assets__asset_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                asset_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_asset_api_v1_assets__asset_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                asset_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AssetUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssetResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    change_password_api_v1_auth_change_password_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangePasswordRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_api_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_api_v1_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                refresh_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refresh_api_v1_auth_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                refresh_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_summary_api_v1_dashboard_summary_get: {
        parameters: {
            query?: {
                tenant_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_reports_api_v1_reports__get: {
        parameters: {
            query?: {
                offset?: number;
                limit?: number;
                asset_id?: string | null;
                report_type?: ("vulnerability" | "executive" | "technical" | "compliance") | null;
                status?: ("pending" | "generating" | "completed" | "failed") | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReportListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_report_api_v1_reports__post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReportCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReportResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_report_api_v1_reports__report_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                report_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReportResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_report_api_v1_reports__report_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                report_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_report_api_v1_reports__report_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                report_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReportUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReportResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_scans_api_v1_scans__get: {
        parameters: {
            query?: {
                offset?: number;
                limit?: number;
                asset_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScanListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_scan_api_v1_scans__post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DiscoveryScanCreate"] | components["schemas"]["VulnerabilityScanCreate"] | components["schemas"]["WebScanCreate"] | components["schemas"]["FullScanCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScanResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_scan_api_v1_scans__scan_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scan_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScanResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_scan_api_v1_scans__scan_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scan_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_scan_api_v1_scans__scan_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scan_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScanUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScanResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_scan_api_v1_scans__scan_id__cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scan_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScanResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    request_scan_enrichment_api_v1_scans__scan_id__enrichment_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scan_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScanEnrichmentQueued"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_scan_api_v1_scans__scan_id__run_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scan_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScanResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_tenants_api_v1_tenants__get: {
        parameters: {
            query?: {
                offset?: number;
                limit?: number;
                include_inactive?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TenantResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_tenant_api_v1_tenants__post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TenantCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TenantResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_tenant_api_v1_tenants__tenant_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenant_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TenantResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    deactivate_tenant_api_v1_tenants__tenant_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenant_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_tenant_api_v1_tenants__tenant_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenant_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TenantUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TenantResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_users_api_v1_users__get: {
        parameters: {
            query?: {
                /** @description Filtrar por tenant (solo superadmin) */
                tenant_id?: string | null;
                include_inactive?: boolean;
                offset?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_user_api_v1_users__post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_me_api_v1_users_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
        };
    };
    get_user_api_v1_users__user_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    deactivate_user_api_v1_users__user_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_user_api_v1_users__user_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_vulnerabilities_api_v1_vulnerabilities__get: {
        parameters: {
            query?: {
                offset?: number;
                limit?: number;
                scan_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VulnerabilityListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_vulnerability_api_v1_vulnerabilities__post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VulnerabilityCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VulnerabilityResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_vulnerability_api_v1_vulnerabilities__vulnerability_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                vulnerability_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VulnerabilityResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_vulnerability_api_v1_vulnerabilities__vulnerability_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                vulnerability_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_vulnerability_api_v1_vulnerabilities__vulnerability_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                vulnerability_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VulnerabilityUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VulnerabilityResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_enrichment_api_v1_vulnerabilities__vulnerability_id__enrichment_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                vulnerability_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VulnerabilityEnrichmentRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    request_enrichment_api_v1_vulnerabilities__vulnerability_id__enrichment_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                vulnerability_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnrichmentQueued"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    db_index_health_health_db_indexes_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
