"""add plan and max_assets to tenants

Revision ID: 70dc591dac68
Revises: 712a827b0929
Create Date: 2026-03-22 18:03:10.254007

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70dc591dac68'
down_revision: Union[str, None] = '712a827b0929'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('plan', sa.String(length=50), nullable=False))
    op.add_column('tenants', sa.Column('max_assets', sa.Integer(), nullable=False))
    op.drop_index('ix_users_email_lower', table_name='users')
    op.drop_index('ix_users_tenant_active', table_name='users')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_users_tenant_active', 'users', ['tenant_id', 'is_active'], unique=False)
    op.create_index('ix_users_email_lower', 'users', [sa.text('lower(email::text)')], unique=False)
    op.drop_column('tenants', 'max_assets')
    op.drop_column('tenants', 'plan')
    # ### end Alembic commands ###