/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/_admin'
import { Route as AuthenticatedReaderRouteImport } from './routes/_authenticated/_reader'
import { Route as AuthenticatedForbiddenRouteImport } from './routes/_authenticated/forbidden'
import { Route as AuthenticatedAdminSettingsRouteImport } from './routes/_authenticated/_admin/settings'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/_admin/users'
import { Route as AuthenticatedReaderIndexRouteImport } from './routes/_authenticated/_reader/index'
import { Route as AuthenticatedReaderAssetsRouteImport } from './routes/_authenticated/_reader/assets'
import { Route as AuthenticatedReaderReportsRouteImport } from './routes/_authenticated/_reader/reports'
import { Route as AuthenticatedReaderScansRouteImport } from './routes/_authenticated/_reader/scans'
import { Route as AuthenticatedReaderVulnerabilitiesRouteImport } from './routes/_authenticated/_reader/vulnerabilities'
import { Route as AuthenticatedReaderScansIndexRouteImport } from './routes/_authenticated/_reader/scans.index'
import { Route as AuthenticatedReaderScansIdRouteImport } from './routes/_authenticated/_reader/scans.$id'
import { Route as AuthenticatedReaderVulnerabilitiesIndexRouteImport } from './routes/_authenticated/_reader/vulnerabilities.index'
import { Route as AuthenticatedReaderVulnerabilitiesIdRouteImport } from './routes/_authenticated/_reader/vulnerabilities.$id'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedReaderRoute = AuthenticatedReaderRouteImport.update({
  id: '/_reader',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedForbiddenRoute = AuthenticatedForbiddenRouteImport.update({
  id: '/forbidden',
  path: '/forbidden',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminSettingsRoute =
  AuthenticatedAdminSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedReaderIndexRoute =
  AuthenticatedReaderIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedReaderRoute,
  } as any)
const AuthenticatedReaderAssetsRoute =
  AuthenticatedReaderAssetsRouteImport.update({
    id: '/assets',
    path: '/assets',
    getParentRoute: () => AuthenticatedReaderRoute,
  } as any)
const AuthenticatedReaderReportsRoute =
  AuthenticatedReaderReportsRouteImport.update({
    id: '/reports',
    path: '/reports',
    getParentRoute: () => AuthenticatedReaderRoute,
  } as any)
const AuthenticatedReaderScansRoute =
  AuthenticatedReaderScansRouteImport.update({
    id: '/scans',
    path: '/scans',
    getParentRoute: () => AuthenticatedReaderRoute,
  } as any)
const AuthenticatedReaderVulnerabilitiesRoute =
  AuthenticatedReaderVulnerabilitiesRouteImport.update({
    id: '/vulnerabilities',
    path: '/vulnerabilities',
    getParentRoute: () => AuthenticatedReaderRoute,
  } as any)
const AuthenticatedReaderScansIndexRoute =
  AuthenticatedReaderScansIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedReaderScansRoute,
  } as any)
const AuthenticatedReaderScansIdRoute =
  AuthenticatedReaderScansIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedReaderScansRoute,
  } as any)
const AuthenticatedReaderVulnerabilitiesIndexRoute =
  AuthenticatedReaderVulnerabilitiesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedReaderVulnerabilitiesRoute,
  } as any)
const AuthenticatedReaderVulnerabilitiesIdRoute =
  AuthenticatedReaderVulnerabilitiesIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedReaderVulnerabilitiesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedReaderIndexRoute
  '/login': typeof LoginRoute
  '/forbidden': typeof AuthenticatedForbiddenRoute
  '/settings': typeof AuthenticatedAdminSettingsRoute
  '/users': typeof AuthenticatedAdminUsersRoute
  '/assets': typeof AuthenticatedReaderAssetsRoute
  '/reports': typeof AuthenticatedReaderReportsRoute
  '/scans': typeof AuthenticatedReaderScansRouteWithChildren
  '/vulnerabilities': typeof AuthenticatedReaderVulnerabilitiesRouteWithChildren
  '/scans/$id': typeof AuthenticatedReaderScansIdRoute
  '/vulnerabilities/$id': typeof AuthenticatedReaderVulnerabilitiesIdRoute
  '/scans/': typeof AuthenticatedReaderScansIndexRoute
  '/vulnerabilities/': typeof AuthenticatedReaderVulnerabilitiesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof AuthenticatedReaderIndexRoute
  '/login': typeof LoginRoute
  '/forbidden': typeof AuthenticatedForbiddenRoute
  '/settings': typeof AuthenticatedAdminSettingsRoute
  '/users': typeof AuthenticatedAdminUsersRoute
  '/assets': typeof AuthenticatedReaderAssetsRoute
  '/reports': typeof AuthenticatedReaderReportsRoute
  '/scans/$id': typeof AuthenticatedReaderScansIdRoute
  '/vulnerabilities/$id': typeof AuthenticatedReaderVulnerabilitiesIdRoute
  '/scans': typeof AuthenticatedReaderScansIndexRoute
  '/vulnerabilities': typeof AuthenticatedReaderVulnerabilitiesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/_admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/_reader': typeof AuthenticatedReaderRouteWithChildren
  '/_authenticated/forbidden': typeof AuthenticatedForbiddenRoute
  '/_authenticated/_admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/_authenticated/_admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/_reader/assets': typeof AuthenticatedReaderAssetsRoute
  '/_authenticated/_reader/reports': typeof AuthenticatedReaderReportsRoute
  '/_authenticated/_reader/scans': typeof AuthenticatedReaderScansRouteWithChildren
  '/_authenticated/_reader/vulnerabilities': typeof AuthenticatedReaderVulnerabilitiesRouteWithChildren
  '/_authenticated/_reader/': typeof AuthenticatedReaderIndexRoute
  '/_authenticated/_reader/scans/$id': typeof AuthenticatedReaderScansIdRoute
  '/_authenticated/_reader/vulnerabilities/$id': typeof AuthenticatedReaderVulnerabilitiesIdRoute
  '/_authenticated/_reader/scans/': typeof AuthenticatedReaderScansIndexRoute
  '/_authenticated/_reader/vulnerabilities/': typeof AuthenticatedReaderVulnerabilitiesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/forbidden'
    | '/settings'
    | '/users'
    | '/assets'
    | '/reports'
    | '/scans'
    | '/vulnerabilities'
    | '/scans/$id'
    | '/vulnerabilities/$id'
    | '/scans/'
    | '/vulnerabilities/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/forbidden'
    | '/settings'
    | '/users'
    | '/assets'
    | '/reports'
    | '/scans/$id'
    | '/vulnerabilities/$id'
    | '/scans'
    | '/vulnerabilities'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/_admin'
    | '/_authenticated/_reader'
    | '/_authenticated/forbidden'
    | '/_authenticated/_admin/settings'
    | '/_authenticated/_admin/users'
    | '/_authenticated/_reader/assets'
    | '/_authenticated/_reader/reports'
    | '/_authenticated/_reader/scans'
    | '/_authenticated/_reader/vulnerabilities'
    | '/_authenticated/_reader/'
    | '/_authenticated/_reader/scans/$id'
    | '/_authenticated/_reader/vulnerabilities/$id'
    | '/_authenticated/_reader/scans/'
    | '/_authenticated/_reader/vulnerabilities/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/_admin': {
      id: '/_authenticated/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/_reader': {
      id: '/_authenticated/_reader'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedReaderRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/forbidden': {
      id: '/_authenticated/forbidden'
      path: '/forbidden'
      fullPath: '/forbidden'
      preLoaderRoute: typeof AuthenticatedForbiddenRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/_admin/settings': {
      id: '/_authenticated/_admin/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/users': {
      id: '/_authenticated/_admin/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_reader/': {
      id: '/_authenticated/_reader/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedReaderIndexRouteImport
      parentRoute: typeof AuthenticatedReaderRoute
    }
    '/_authenticated/_reader/assets': {
      id: '/_authenticated/_reader/assets'
      path: '/assets'
      fullPath: '/assets'
      preLoaderRoute: typeof AuthenticatedReaderAssetsRouteImport
      parentRoute: typeof AuthenticatedReaderRoute
    }
    '/_authenticated/_reader/reports': {
      id: '/_authenticated/_reader/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReaderReportsRouteImport
      parentRoute: typeof AuthenticatedReaderRoute
    }
    '/_authenticated/_reader/scans': {
      id: '/_authenticated/_reader/scans'
      path: '/scans'
      fullPath: '/scans'
      preLoaderRoute: typeof AuthenticatedReaderScansRouteImport
      parentRoute: typeof AuthenticatedReaderRoute
    }
    '/_authenticated/_reader/vulnerabilities': {
      id: '/_authenticated/_reader/vulnerabilities'
      path: '/vulnerabilities'
      fullPath: '/vulnerabilities'
      preLoaderRoute: typeof AuthenticatedReaderVulnerabilitiesRouteImport
      parentRoute: typeof AuthenticatedReaderRoute
    }
    '/_authenticated/_reader/scans/': {
      id: '/_authenticated/_reader/scans/'
      path: '/'
      fullPath: '/scans/'
      preLoaderRoute: typeof AuthenticatedReaderScansIndexRouteImport
      parentRoute: typeof AuthenticatedReaderScansRoute
    }
    '/_authenticated/_reader/scans/$id': {
      id: '/_authenticated/_reader/scans/$id'
      path: '/$id'
      fullPath: '/scans/$id'
      preLoaderRoute: typeof AuthenticatedReaderScansIdRouteImport
      parentRoute: typeof AuthenticatedReaderScansRoute
    }
    '/_authenticated/_reader/vulnerabilities/': {
      id: '/_authenticated/_reader/vulnerabilities/'
      path: '/'
      fullPath: '/vulnerabilities/'
      preLoaderRoute: typeof AuthenticatedReaderVulnerabilitiesIndexRouteImport
      parentRoute: typeof AuthenticatedReaderVulnerabilitiesRoute
    }
    '/_authenticated/_reader/vulnerabilities/$id': {
      id: '/_authenticated/_reader/vulnerabilities/$id'
      path: '/$id'
      fullPath: '/vulnerabilities/$id'
      preLoaderRoute: typeof AuthenticatedReaderVulnerabilitiesIdRouteImport
      parentRoute: typeof AuthenticatedReaderVulnerabilitiesRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminSettingsRoute: typeof AuthenticatedAdminSettingsRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminSettingsRoute: AuthenticatedAdminSettingsRoute,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedReaderScansRouteChildren {
  AuthenticatedReaderScansIdRoute: typeof AuthenticatedReaderScansIdRoute
  AuthenticatedReaderScansIndexRoute: typeof AuthenticatedReaderScansIndexRoute
}

const AuthenticatedReaderScansRouteChildren: AuthenticatedReaderScansRouteChildren =
  {
    AuthenticatedReaderScansIdRoute: AuthenticatedReaderScansIdRoute,
    AuthenticatedReaderScansIndexRoute: AuthenticatedReaderScansIndexRoute,
  }

const AuthenticatedReaderScansRouteWithChildren =
  AuthenticatedReaderScansRoute._addFileChildren(
    AuthenticatedReaderScansRouteChildren,
  )

interface AuthenticatedReaderVulnerabilitiesRouteChildren {
  AuthenticatedReaderVulnerabilitiesIdRoute: typeof AuthenticatedReaderVulnerabilitiesIdRoute
  AuthenticatedReaderVulnerabilitiesIndexRoute: typeof AuthenticatedReaderVulnerabilitiesIndexRoute
}

const AuthenticatedReaderVulnerabilitiesRouteChildren: AuthenticatedReaderVulnerabilitiesRouteChildren =
  {
    AuthenticatedReaderVulnerabilitiesIdRoute:
      AuthenticatedReaderVulnerabilitiesIdRoute,
    AuthenticatedReaderVulnerabilitiesIndexRoute:
      AuthenticatedReaderVulnerabilitiesIndexRoute,
  }

const AuthenticatedReaderVulnerabilitiesRouteWithChildren =
  AuthenticatedReaderVulnerabilitiesRoute._addFileChildren(
    AuthenticatedReaderVulnerabilitiesRouteChildren,
  )

interface AuthenticatedReaderRouteChildren {
  AuthenticatedReaderAssetsRoute: typeof AuthenticatedReaderAssetsRoute
  AuthenticatedReaderReportsRoute: typeof AuthenticatedReaderReportsRoute
  AuthenticatedReaderScansRoute: typeof AuthenticatedReaderScansRouteWithChildren
  AuthenticatedReaderVulnerabilitiesRoute: typeof AuthenticatedReaderVulnerabilitiesRouteWithChildren
  AuthenticatedReaderIndexRoute: typeof AuthenticatedReaderIndexRoute
}

const AuthenticatedReaderRouteChildren: AuthenticatedReaderRouteChildren = {
  AuthenticatedReaderAssetsRoute: AuthenticatedReaderAssetsRoute,
  AuthenticatedReaderReportsRoute: AuthenticatedReaderReportsRoute,
  AuthenticatedReaderScansRoute: AuthenticatedReaderScansRouteWithChildren,
  AuthenticatedReaderVulnerabilitiesRoute:
    AuthenticatedReaderVulnerabilitiesRouteWithChildren,
  AuthenticatedReaderIndexRoute: AuthenticatedReaderIndexRoute,
}

const AuthenticatedReaderRouteWithChildren =
  AuthenticatedReaderRoute._addFileChildren(AuthenticatedReaderRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedReaderRoute: typeof AuthenticatedReaderRouteWithChildren
  AuthenticatedForbiddenRoute: typeof AuthenticatedForbiddenRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedReaderRoute: AuthenticatedReaderRouteWithChildren,
  AuthenticatedForbiddenRoute: AuthenticatedForbiddenRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
