"""Unit tests for the Scans domain (F2 Slice 2).

PR0 - persistence contract: the partial unique index that forbids two open
(``pending``) scans sharing a name for the same asset.

Design note: the harness here is deliberately minimal. ``tests/unit/test_assets.py``
carries a heavier alembic harness built for Slice 1's ten-statement migration;
PR0 needs a single ``CREATE UNIQUE INDEX``, so only the pieces this slice
exercises are reproduced. If a third suite needs the same infrastructure,
extract it into a shared helper instead of copying it again.
"""

from __future__ import annotations

import importlib.util
import uuid
from datetime import UTC, datetime
from pathlib import Path
from types import ModuleType
from unittest.mock import AsyncMock, MagicMock

import pytest
from pydantic import ValidationError

from app.event_schemas import (
    BaseEvent,
    ScanCreatedEvent,
    ScanDeletedEvent,
    ScanUpdatedEvent,
)
from app.modules.scans.models import Scan

# Name of the index that enforces the business rule: one open definition per
# (tenant_id, asset_id, name). The predicate makes it partial so the name is
# released once the scan leaves ``pending``.
OPEN_NAME_INDEX = "uq_scans_tenant_asset_name_pending"


# The migration that introduces the index is authored later in this work-unit.
# Its revision id is generated by alembic, so it is located by its parent
# instead of by filename.
SLICE_1_HEAD = "e0eafdf389fc"
VERSIONS_DIR = Path(__file__).resolve().parents[2] / "migrations" / "versions"


def _load_slice2_migration() -> ModuleType:
    """Import the Slice 2 migration by locating the revision whose parent is SLICE_1_HEAD."""
    for path in sorted(VERSIONS_DIR.glob("*.py")):
        spec = importlib.util.spec_from_file_location(f"_migration_{path.stem}", path)
        if spec is None or spec.loader is None:  # pragma: no cover - defensive
            continue
        module = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(module)
        if getattr(module, "down_revision", None) == SLICE_1_HEAD:
            return module
    raise AssertionError(
        f"No migration with down_revision={SLICE_1_HEAD!r} found in {VERSIONS_DIR}"
    )


class TestScanOpenNameUniqueIndex:
    """The model must declare the partial unique index, not just the migration."""

    def test_model_declares_the_partial_unique_index(self) -> None:
        indexes = {index.name: index for index in Scan.__table__.indexes}

        assert OPEN_NAME_INDEX in indexes, (
            f"{OPEN_NAME_INDEX} is missing from Scan.__table_args__. "
            "Without it, alembic autogenerate reports drift and alembic check fails."
        )

    def test_index_is_unique_over_tenant_asset_name(self) -> None:
        index = {i.name: i for i in Scan.__table__.indexes}[OPEN_NAME_INDEX]

        assert index.unique is True
        assert [column.name for column in index.columns] == [
            "tenant_id",
            "asset_id",
            "name",
        ]

    def test_index_predicate_is_limited_to_pending(self) -> None:
        index = {i.name: i for i in Scan.__table__.indexes}[OPEN_NAME_INDEX]
        predicate = str(index.dialect_options["postgresql"]["where"])

        assert predicate, "the index must be partial, not a plain unique constraint"
        assert "pending" in predicate
        assert "status" in predicate


class TestOpenNamePreconditionDecision:
    """The precondition decides whether to abort, and explains why in the message."""

    def test_no_duplicates_means_no_abort(self) -> None:
        module = _load_slice2_migration()

        assert module.duplicate_open_name_message([]) is None

    def test_duplicates_produce_an_actionable_message(self) -> None:
        module = _load_slice2_migration()

        message = module.duplicate_open_name_message(
            [("tenant-1", "asset-1", "weekly", 2), ("tenant-2", "asset-2", "nightly", 3)]
        )

        assert message is not None
        assert "weekly" in message
        assert "nightly" in message
        assert "pending" in message
        assert "uq_scans_tenant_asset_name_pending" in message


class TestScanEventSchemas:
    """The three Scans CRUD events, on the shared BaseEvent envelope."""

    @staticmethod
    def _envelope() -> dict[str, object]:
        return {"event_id": uuid.uuid4(), "tenant_id": uuid.uuid4()}

    def test_scan_events_inherit_the_base_envelope(self) -> None:
        for event_cls in (ScanCreatedEvent, ScanUpdatedEvent, ScanDeletedEvent):
            assert issubclass(event_cls, BaseEvent)

    def test_scan_created_event_carries_the_definition_payload(self) -> None:
        event = ScanCreatedEvent(
            **self._envelope(),
            scan_id=uuid.uuid4(),
            asset_id=uuid.uuid4(),
            name="weekly",
            type="discovery",
            status="pending",
            config={"host_discovery": True},
            created_at=datetime.now(UTC),
        )

        assert event.event_type == "scan.created"
        assert event.type == "discovery"
        assert event.status == "pending"
        assert event.config == {"host_discovery": True}

    def test_scan_updated_event_carries_changed_fields(self) -> None:
        event = ScanUpdatedEvent(
            **self._envelope(),
            scan_id=uuid.uuid4(),
            changed_fields=["name", "config"],
        )

        assert event.event_type == "scan.updated"
        assert event.changed_fields == ["name", "config"]

    def test_scan_deleted_event_carries_scan_id(self) -> None:
        scan_id = uuid.uuid4()

        event = ScanDeletedEvent(**self._envelope(), scan_id=scan_id)

        assert event.event_type == "scan.deleted"
        assert event.scan_id == scan_id

    def test_scan_created_event_rejects_an_unknown_scan_type(self) -> None:
        with pytest.raises(ValidationError):
            ScanCreatedEvent(
                **self._envelope(),
                scan_id=uuid.uuid4(),
                asset_id=uuid.uuid4(),
                name="weekly",
                type="not-a-scan-type",
                status="pending",
                config=None,
                created_at=datetime.now(UTC),
            )


class TestScanSchemas:
    """The public Scans API contract: discriminated create, partial update, whitelist."""

    @staticmethod
    def _body() -> dict[str, object]:
        return {
            "tenant_id": uuid.uuid4(),
            "asset_id": uuid.uuid4(),
            "name": "weekly",
        }

    @pytest.mark.parametrize(
        ("scan_type", "config"),
        [
            ("discovery", {"host_discovery": True}),
            ("vulnerability", {"checks": ["baseline"]}),
            ("web", {"paths": ["/"]}),
            ("full", {"host_discovery": True, "checks": ["baseline"], "paths": ["/"]}),
        ],
    )
    def test_scan_create_accepts_each_of_the_four_types(
        self, scan_type: str, config: dict[str, object]
    ) -> None:
        from pydantic import TypeAdapter

        from app.modules.scans.schemas import ScanCreateRequest

        request = TypeAdapter(ScanCreateRequest).validate_python(
            {**self._body(), "type": scan_type, "config": config}
        )

        assert request.type == scan_type

    def test_scan_create_rejects_an_unknown_type(self) -> None:
        from pydantic import TypeAdapter, ValidationError

        from app.modules.scans.schemas import ScanCreateRequest

        with pytest.raises(ValidationError):
            TypeAdapter(ScanCreateRequest).validate_python(
                {**self._body(), "type": "not-a-scan-type", "config": {}}
            )

    def test_scan_create_body_rejects_unknown_keys(self) -> None:
        from pydantic import TypeAdapter, ValidationError

        from app.modules.scans.schemas import ScanCreateRequest

        with pytest.raises(ValidationError):
            TypeAdapter(ScanCreateRequest).validate_python(
                {
                    **self._body(),
                    "type": "discovery",
                    "config": {"host_discovery": True},
                    "status": "pending",
                }
            )

    def test_scan_create_config_rejects_unknown_keys(self) -> None:
        from pydantic import TypeAdapter, ValidationError

        from app.modules.scans.schemas import ScanCreateRequest

        with pytest.raises(ValidationError):
            TypeAdapter(ScanCreateRequest).validate_python(
                {
                    **self._body(),
                    "type": "discovery",
                    "config": {"host_discovery": True, "ports": [80]},
                }
            )

    def test_scan_create_rejects_a_config_missing_a_required_key(self) -> None:
        from pydantic import TypeAdapter, ValidationError

        from app.modules.scans.schemas import ScanCreateRequest

        with pytest.raises(ValidationError):
            TypeAdapter(ScanCreateRequest).validate_python(
                {**self._body(), "type": "discovery", "config": {}}
            )

    def test_scan_update_rejects_identity_and_lifecycle_fields(self) -> None:
        from pydantic import ValidationError

        from app.modules.scans.schemas import ScanUpdate

        for forbidden in (
            "tenant_id",
            "asset_id",
            "status",
            "started_at",
            "completed_at",
        ):
            with pytest.raises(ValidationError):
                ScanUpdate.model_validate({forbidden: "anything"})

    def test_scan_update_accepts_a_partial_body(self) -> None:
        from app.modules.scans.schemas import ScanUpdate

        update = ScanUpdate.model_validate({"name": "renamed"})

        assert update.name == "renamed"
        assert update.type is None
        assert update.config is None

    def test_scan_response_exposes_exactly_the_eleven_public_fields(self) -> None:
        from app.modules.scans.schemas import ScanResponse

        assert set(ScanResponse.model_fields) == {
            "id",
            "tenant_id",
            "asset_id",
            "name",
            "type",
            "status",
            "config",
            "started_at",
            "completed_at",
            "created_at",
            "updated_at",
        }

    def test_scan_response_renames_orm_scan_type_to_public_type(self) -> None:
        from app.modules.scans.schemas import ScanResponse

        orm = Scan(
            id=uuid.uuid4(),
            tenant_id=uuid.uuid4(),
            asset_id=uuid.uuid4(),
            name="weekly",
            scan_type="discovery",
            status="pending",
            config={"host_discovery": True},
        )
        # Bypass DB defaults for the test: these are populated on INSERT.
        orm.created_at = datetime.now(UTC)
        orm.updated_at = datetime.now(UTC)

        response = ScanResponse.from_orm_instance(orm)
        dumped = response.model_dump(mode="json")

        assert dumped["type"] == "discovery"
        assert dumped["status"] == "pending"
        assert "scan_type" not in dumped


VALID_SCAN_CONFIGS = [
    ("discovery", {"host_discovery": True}),
    ("vulnerability", {"checks": ["baseline"]}),
    ("web", {"paths": ["/"]}),
    ("full", {"host_discovery": True, "checks": ["baseline"], "paths": ["/"]}),
]

INVALID_SCAN_CONFIGS = [
    ("not-a-scan-type", {}, "unknown scan_type 'not-a-scan-type'"),
    ("discovery", "not-an-object", "config must be an object for scan_type 'discovery'"),
    (
        "discovery",
        {"host_discovery": True, "ports": [80]},
        "config.ports is not allowed for scan_type 'discovery'",
    ),
    ("discovery", {}, "config.host_discovery is required for scan_type 'discovery'"),
    (
        "discovery",
        {"host_discovery": "yes"},
        "config.host_discovery must be a boolean for scan_type 'discovery'",
    ),
    ("vulnerability", {}, "config.checks is required for scan_type 'vulnerability'"),
    (
        "vulnerability",
        {"checks": []},
        "config.checks must be a non-empty list of non-empty strings "
        "for scan_type 'vulnerability'",
    ),
    (
        "vulnerability",
        {"checks": ["baseline", ""]},
        "config.checks must be a non-empty list of non-empty strings "
        "for scan_type 'vulnerability'",
    ),
    ("web", {}, "config.paths is required for scan_type 'web'"),
    (
        "web",
        {"paths": []},
        "config.paths must be a non-empty list of paths beginning with '/' "
        "for scan_type 'web'",
    ),
    (
        "web",
        {"paths": ["/ok", "missing-slash"]},
        "config.paths must be a non-empty list of paths beginning with '/' "
        "for scan_type 'web'",
    ),
    (
        "full",
        {"host_discovery": True, "checks": ["baseline"]},
        "config.paths is required for scan_type 'full'",
    ),
]


class TestValidateScanConfig:
    """The semantic frontier for scan config, shared by POST and PATCH."""

    @pytest.mark.parametrize(("scan_type", "config"), VALID_SCAN_CONFIGS)
    def test_valid_config_is_accepted_and_returned(
        self, scan_type: str, config: dict[str, object]
    ) -> None:
        from app.modules.scans.service import _validate_scan_config

        assert _validate_scan_config(scan_type, config) == config

    @pytest.mark.parametrize(("scan_type", "config", "message"), INVALID_SCAN_CONFIGS)
    def test_invalid_config_raises_the_contract_message(
        self, scan_type: str, config: object, message: str
    ) -> None:
        from app.modules.scans.service import _validate_scan_config

        with pytest.raises(ValueError) as excinfo:
            _validate_scan_config(scan_type, config)

        assert str(excinfo.value) == message

    def test_returned_lists_are_copies_not_the_caller_list(self) -> None:
        from app.modules.scans.service import _validate_scan_config

        original = ["baseline"]
        result = _validate_scan_config("vulnerability", {"checks": original})
        original.append("mutated")

        assert result["checks"] == ["baseline"]

    def test_validate_scan_config_raises_scan_config_error(self) -> None:
        from app.modules.scans.service import ScanConfigError, _validate_scan_config

        with pytest.raises(ScanConfigError) as excinfo:
            _validate_scan_config("not-a-scan-type", {})

        assert str(excinfo.value) == "unknown scan_type 'not-a-scan-type'"

    def test_scan_config_error_is_a_value_error_subclass(self) -> None:
        from app.modules.scans.service import ScanConfigError

        assert issubclass(ScanConfigError, ValueError)


# ---------------------------------------------------------------------------
# PR2 part 2 — service unit tests: mocked session + bus, no database.
# ---------------------------------------------------------------------------


def _db_returning(*, scalar_one_or_none=None, scalars_all=None, total=0) -> AsyncMock:
    """An AsyncSession double whose ``execute`` always returns one result."""
    db = AsyncMock()
    result = MagicMock()
    result.scalar_one_or_none.return_value = scalar_one_or_none
    result.scalars.return_value.all.return_value = (
        scalars_all if scalars_all is not None else []
    )
    result.scalar_one.return_value = total
    db.execute.return_value = result
    return db


def _sequenced_db() -> tuple[AsyncMock, list[str]]:
    """``_db_returning`` whose flush/commit append to a shared call-order list."""
    calls: list[str] = []

    async def _flush() -> None:
        calls.append("flush")

    async def _commit() -> None:
        calls.append("commit")

    db = _db_returning()
    db.flush.side_effect = _flush
    db.commit.side_effect = _commit
    return db, calls


def _spy_bus(calls: list[str]) -> AsyncMock:
    async def _publish(*_args: object, **_kwargs: object) -> None:
        calls.append("publish")

    bus = AsyncMock()
    bus.publish.side_effect = _publish
    return bus


def _predicate_columns(stmt: object) -> set[str]:
    """Column names compared in the statement's WHERE clause.

    ``str(stmt)`` is unusable for this: a plain ``select(Scan)`` renders every
    column name in the SELECT list, including the predicate columns.
    """
    clause = getattr(stmt, "whereclause", None)
    if clause is None:
        return set()
    clauses = getattr(clause, "clauses", [clause])
    return {expr.left.name for expr in clauses}


def _db_recording_statements(db: AsyncMock) -> list[object]:
    """Record every statement passed to ``db.execute``."""
    result = db.execute.return_value
    captured: list[object] = []

    def _record(stmt: object, *_args: object, **_kwargs: object) -> object:
        captured.append(stmt)
        return result

    db.execute.side_effect = _record
    return captured


def _sequenced_fetch_db(scan: Scan) -> tuple[AsyncMock, list[str]]:
    """``_db_returning`` returning ``scan`` from fetches, with flush/commit recorded."""
    db = _db_returning(scalar_one_or_none=scan)
    calls: list[str] = []

    async def _flush() -> None:
        calls.append("flush")

    async def _commit() -> None:
        calls.append("commit")

    db.flush.side_effect = _flush
    db.commit.side_effect = _commit
    return db, calls


def _sequenced_create_db() -> tuple[AsyncMock, list[str], list[Scan]]:
    """``_sequenced_db`` whose flush simulates INSERT populating id/created_at."""
    db, calls = _sequenced_db()
    added: list[Scan] = []
    db.add = MagicMock(side_effect=added.append)
    base_flush = db.flush.side_effect

    async def _flush_with_defaults() -> None:
        if base_flush is not None:
            await base_flush()
        for obj in added:
            if getattr(obj, "id", None) is None:
                obj.id = uuid.uuid4()
            if getattr(obj, "created_at", None) is None:
                obj.created_at = datetime.now(UTC)

    db.flush.side_effect = _flush_with_defaults
    return db, calls, added


def _scan(scan_type: str, config: dict[str, object] | None) -> Scan:
    """A persisted-shaped Scan instance without touching a database."""
    scan = Scan(
        id=uuid.uuid4(),
        tenant_id=uuid.uuid4(),
        asset_id=uuid.uuid4(),
        name="weekly",
        scan_type=scan_type,
        status="pending",
        config=config,
    )
    # Bypass DB defaults for the test: these are populated on INSERT.
    scan.created_at = datetime.now(UTC)
    scan.updated_at = datetime.now(UTC)
    return scan


class TestCreateScan:
    """create_scan: forced lifecycle, call order, validation frontier, duplicates."""

    @pytest.mark.asyncio
    async def test_create_scan_forces_pending_and_clears_operational_timestamps(
        self,
    ) -> None:
        from app.modules.scans.schemas import DiscoveryScanCreate
        from app.modules.scans.service import create_scan

        tenant_id = uuid.uuid4()
        db, calls, _added = _sequenced_create_db()
        bus = _spy_bus(calls)
        data = DiscoveryScanCreate(
            tenant_id=tenant_id,
            asset_id=uuid.uuid4(),
            name="weekly",
            config={"host_discovery": True},
        )

        scan = await create_scan(data, tenant_id, db, bus)

        assert scan.status == "pending"
        assert scan.started_at is None
        assert scan.completed_at is None
        assert scan.tenant_id == tenant_id
        assert scan.scan_type == "discovery"
        assert scan.config == {"host_discovery": True}

    @pytest.mark.asyncio
    async def test_create_scan_flushes_then_commits_then_publishes_to_scan_events(
        self,
    ) -> None:
        from app.modules.scans.schemas import DiscoveryScanCreate
        from app.modules.scans.service import create_scan

        tenant_id = uuid.uuid4()
        db, calls, _added = _sequenced_create_db()
        bus = _spy_bus(calls)
        data = DiscoveryScanCreate(
            tenant_id=tenant_id,
            asset_id=uuid.uuid4(),
            name="weekly",
            config={"host_discovery": True},
        )

        scan = await create_scan(data, tenant_id, db, bus)

        assert calls == ["flush", "commit", "publish"]
        assert bus.publish.await_args.kwargs["stream"] == "scan.events"
        event = bus.publish.await_args.args[0]
        assert event.event_type == "scan.created"
        assert event.scan_id == scan.id
        assert event.status == "pending"
        assert event.created_at == scan.created_at

    @pytest.mark.asyncio
    async def test_create_scan_validates_config_before_touching_the_session(self) -> None:
        from app.modules.scans.schemas import VulnerabilityScanCreate
        from app.modules.scans.service import create_scan

        db, calls, added = _sequenced_create_db()
        bus = _spy_bus(calls)
        # Schema-valid (a non-empty list of strings) but service-invalid: an
        # empty check identifier. This is exactly the gap the service owns.
        data = VulnerabilityScanCreate(
            tenant_id=uuid.uuid4(),
            asset_id=uuid.uuid4(),
            name="weekly",
            config={"checks": [""]},
        )

        with pytest.raises(ValueError):
            await create_scan(data, data.tenant_id, db, bus)

        assert calls == []
        assert added == []

    @pytest.mark.asyncio
    async def test_create_scan_maps_the_open_name_index_violation_to_scan_duplicate_error(
        self,
    ) -> None:
        from sqlalchemy.exc import IntegrityError

        from app.modules.scans.schemas import DiscoveryScanCreate
        from app.modules.scans.service import ScanDuplicateError, create_scan

        tenant_id = uuid.uuid4()
        db, calls, _added = _sequenced_create_db()
        bus = _spy_bus(calls)
        err = IntegrityError("INSERT", {}, Exception("duplicate key value"))
        err.orig = MagicMock(constraint_name=OPEN_NAME_INDEX)
        db.flush.side_effect = err
        data = DiscoveryScanCreate(
            tenant_id=tenant_id,
            asset_id=uuid.uuid4(),
            name="weekly",
            config={"host_discovery": True},
        )

        with pytest.raises(ScanDuplicateError) as excinfo:
            await create_scan(data, tenant_id, db, bus)

        assert isinstance(excinfo.value.__cause__, IntegrityError)
        assert calls == []

    @pytest.mark.asyncio
    async def test_create_scan_maps_the_asset_fk_violation_to_scan_asset_not_found(
        self,
    ) -> None:
        """A flush-time fk_scans_asset_tenant violation is the deleted-asset race.

        The asset was resolved moments before the INSERT; if it disappears in
        that window the composite FK fires here and the caller deserves the
        same 404 the pre-INSERT resolution produces.
        """
        from sqlalchemy.exc import IntegrityError

        from app.modules.scans.schemas import DiscoveryScanCreate
        from app.modules.scans.service import ScanAssetNotFoundError, create_scan

        tenant_id = uuid.uuid4()
        db, calls, _added = _sequenced_create_db()
        bus = _spy_bus(calls)
        err = IntegrityError("INSERT", {}, Exception("violates foreign key constraint"))
        err.orig = MagicMock(constraint_name="fk_scans_asset_tenant")
        db.flush.side_effect = err
        data = DiscoveryScanCreate(
            tenant_id=tenant_id,
            asset_id=uuid.uuid4(),
            name="weekly",
            config={"host_discovery": True},
        )

        with pytest.raises(ScanAssetNotFoundError) as excinfo:
            await create_scan(data, tenant_id, db, bus)

        assert str(excinfo.value) == "scan asset not found"
        assert isinstance(excinfo.value.__cause__, IntegrityError)
        assert calls == []

    @pytest.mark.asyncio
    async def test_create_scan_open_name_violation_wins_over_the_asset_fk(
        self,
    ) -> None:
        """When the driver message could match both constraints, 409 wins.

        The open-name rule is the business rule: its violation must keep
        mapping to ``ScanDuplicateError`` even when the same message also
        names the asset FK.
        """
        from sqlalchemy.exc import IntegrityError

        from app.modules.scans.schemas import DiscoveryScanCreate
        from app.modules.scans.service import ScanDuplicateError, create_scan

        tenant_id = uuid.uuid4()
        db, calls, _added = _sequenced_create_db()
        bus = _spy_bus(calls)
        # No structured constraint_name available: detection must fall back to
        # the message, which names BOTH constraints.
        err = IntegrityError(
            "INSERT",
            {},
            Exception(f"violates {OPEN_NAME_INDEX} and fk_scans_asset_tenant"),
        )
        db.flush.side_effect = err
        data = DiscoveryScanCreate(
            tenant_id=tenant_id,
            asset_id=uuid.uuid4(),
            name="weekly",
            config={"host_discovery": True},
        )

        with pytest.raises(ScanDuplicateError) as excinfo:
            await create_scan(data, tenant_id, db, bus)

        assert "already exists" in str(excinfo.value)
        assert calls == []

    @pytest.mark.asyncio
    async def test_create_scan_reraises_an_unrecognised_integrity_error_unchanged(
        self,
    ) -> None:
        from sqlalchemy.exc import IntegrityError

        from app.modules.scans.schemas import DiscoveryScanCreate
        from app.modules.scans.service import create_scan

        tenant_id = uuid.uuid4()
        db, calls, _added = _sequenced_create_db()
        bus = _spy_bus(calls)
        err = IntegrityError("INSERT", {}, Exception("violates chk_scans_status"))
        db.flush.side_effect = err
        data = DiscoveryScanCreate(
            tenant_id=tenant_id,
            asset_id=uuid.uuid4(),
            name="weekly",
            config={"host_discovery": True},
        )

        with pytest.raises(IntegrityError) as excinfo:
            await create_scan(data, tenant_id, db, bus)

        assert excinfo.value is err
        assert calls == []


class TestGetScan:
    """get_scan: the tenant predicate is explicit, never implied by RLS."""

    @pytest.mark.asyncio
    async def test_get_scan_applies_the_tenant_predicate_when_tenant_id_is_given(
        self,
    ) -> None:
        from app.modules.scans.service import get_scan

        tenant_id = uuid.uuid4()
        db = _db_returning(scalar_one_or_none=None)
        captured = _db_recording_statements(db)

        result = await get_scan(uuid.uuid4(), tenant_id, db)

        assert result is None
        assert len(captured) == 1
        assert _predicate_columns(captured[0]) == {"id", "tenant_id"}

    @pytest.mark.asyncio
    async def test_get_scan_omits_the_tenant_predicate_for_the_global_path(self) -> None:
        from app.modules.scans.service import get_scan

        db = _db_returning(scalar_one_or_none=None)
        captured = _db_recording_statements(db)

        result = await get_scan(uuid.uuid4(), None, db)

        assert result is None
        assert len(captured) == 1
        assert _predicate_columns(captured[0]) == {"id"}


class TestListScans:
    """list_scans: deterministic order, matching page metadata, optional filter."""

    @pytest.mark.asyncio
    async def test_list_scans_orders_desc_and_applies_offset_and_limit(self) -> None:
        from app.modules.scans.service import list_scans

        items = [MagicMock(), MagicMock()]
        db = _db_returning(scalars_all=items, total=42)
        captured = _db_recording_statements(db)

        returned, total = await list_scans(uuid.uuid4(), db, limit=10, offset=25)

        assert total == 42
        assert list(returned) == items
        assert len(captured) == 2
        count_stmt, items_stmt = captured
        assert "count(*)" in str(count_stmt)
        compiled_items = str(items_stmt)
        assert "created_at DESC" in compiled_items
        assert "id DESC" in compiled_items
        assert "LIMIT" in compiled_items
        assert "OFFSET" in compiled_items

    @pytest.mark.asyncio
    async def test_list_scans_applies_the_asset_filter_to_both_queries(self) -> None:
        from app.modules.scans.service import list_scans

        tenant_id = uuid.uuid4()
        asset_id = uuid.uuid4()
        db = _db_returning(scalars_all=[MagicMock()], total=3)
        captured = _db_recording_statements(db)

        returned, total = await list_scans(
            tenant_id, db, limit=10, offset=0, asset_id=asset_id
        )

        assert total == 3
        assert len(captured) == 2
        for stmt in captured:
            assert "asset_id" in _predicate_columns(stmt)
            assert "tenant_id" in _predicate_columns(stmt)

    @pytest.mark.asyncio
    async def test_list_scans_without_asset_id_adds_no_asset_predicate(self) -> None:
        from app.modules.scans.service import list_scans

        tenant_id = uuid.uuid4()
        db = _db_returning(scalars_all=[], total=0)
        captured = _db_recording_statements(db)

        await list_scans(tenant_id, db, limit=10, offset=0)

        assert len(captured) == 2
        for stmt in captured:
            assert "asset_id" not in _predicate_columns(stmt)
            assert "tenant_id" in _predicate_columns(stmt)


class TestUpdateScan:
    """update_scan: ordered change report and effective-pair revalidation."""

    @pytest.mark.asyncio
    async def test_update_scan_reports_changed_fields_in_the_fixed_public_order(
        self,
    ) -> None:
        from app.modules.scans.schemas import ScanUpdate
        from app.modules.scans.service import update_scan

        scan = _scan("discovery", {"host_discovery": True})
        db, calls = _sequenced_fetch_db(scan)
        bus = _spy_bus(calls)
        # The name is sent but equals the stored one: it must be omitted,
        # and the remaining two must appear in the fixed name/type/config order.
        data = ScanUpdate(name="weekly", type="vulnerability", config={"checks": ["x"]})

        result = await update_scan(scan.id, scan.tenant_id, data, db, bus)

        assert result is scan
        assert calls == ["flush", "commit", "publish"]
        event = bus.publish.await_args.args[0]
        assert event.changed_fields == ["type", "config"]
        assert scan.name == "weekly"
        assert scan.scan_type == "vulnerability"
        assert scan.config == {"checks": ["x"]}

    @pytest.mark.asyncio
    async def test_update_scan_revalidates_the_effective_type_config_pair(self) -> None:
        from app.modules.scans.schemas import ScanUpdate
        from app.modules.scans.service import update_scan

        scan = _scan("vulnerability", {"checks": ["baseline"]})
        db, calls = _sequenced_fetch_db(scan)
        bus = _spy_bus(calls)
        # Only the type changes; the stored checks-config is incompatible with
        # the new type, so the effective pair must be rejected before any write.
        data = ScanUpdate(type="web")

        with pytest.raises(ValueError):
            await update_scan(scan.id, scan.tenant_id, data, db, bus)

        assert calls == []

    @pytest.mark.asyncio
    async def test_update_scan_leaves_the_orm_object_untouched_when_the_pair_is_rejected(
        self,
    ) -> None:
        """A rejected PATCH must leave the in-memory object exactly as it was.

        The rejection happens before any write, so the identity-map state must stay
        consistent with the database row. Asserting ``calls == []`` alone does NOT
        prove this: it proves no I/O happened, not that the object is intact.
        """
        from app.modules.scans.schemas import ScanUpdate
        from app.modules.scans.service import update_scan

        scan = _scan("vulnerability", {"checks": ["baseline"]})
        db, calls = _sequenced_fetch_db(scan)
        bus = _spy_bus(calls)
        data = ScanUpdate(type="web")

        with pytest.raises(ValueError):
            await update_scan(scan.id, scan.tenant_id, data, db, bus)

        assert calls == []
        assert scan.scan_type == "vulnerability", (
            "the rejected type MUST NOT be applied to the ORM object"
        )
        assert scan.config == {"checks": ["baseline"]}
        assert scan.name == "weekly"

    @pytest.mark.asyncio
    async def test_update_scan_publishes_nothing_when_no_public_field_changed(
        self,
    ) -> None:
        """A PATCH whose values already match the row is not an update."""
        from app.modules.scans.schemas import ScanUpdate
        from app.modules.scans.service import update_scan

        scan = _scan("discovery", {"host_discovery": True})  # name is "weekly"
        db, calls = _sequenced_fetch_db(scan)
        bus = _spy_bus(calls)
        data = ScanUpdate(name="weekly")

        result = await update_scan(scan.id, scan.tenant_id, data, db, bus)

        assert result is scan
        assert calls == ["flush", "commit"], (
            "an unchanged PATCH MUST NOT emit scan.updated"
        )

    @pytest.mark.asyncio
    async def test_update_scan_returns_none_when_the_scan_is_not_visible(self) -> None:
        from app.modules.scans.schemas import ScanUpdate
        from app.modules.scans.service import update_scan

        db, calls = _sequenced_db()
        bus = _spy_bus(calls)

        result = await update_scan(
            uuid.uuid4(), uuid.uuid4(), ScanUpdate(name="renamed"), db, bus
        )

        assert result is None
        assert calls == []


class TestDeleteScan:
    """delete_scan: miss is silent, hit commits before publishing."""

    @pytest.mark.asyncio
    async def test_delete_scan_miss_is_silent_and_hit_commits_before_publishing(
        self,
    ) -> None:
        from app.modules.scans.service import delete_scan

        scan = _scan("discovery", {"host_discovery": True})
        tenant_id = scan.tenant_id

        # Miss: not visible, nothing recorded, nothing published.
        db, calls = _sequenced_db()
        bus = _spy_bus(calls)
        assert await delete_scan(scan.id, tenant_id, db, bus) is False
        assert calls == []

        # Hit: commit strictly before publish, with the captured identity.
        db, calls = _sequenced_fetch_db(scan)
        bus = _spy_bus(calls)
        assert await delete_scan(scan.id, tenant_id, db, bus) is True
        assert calls == ["commit", "publish"]
        event = bus.publish.await_args.args[0]
        assert event.event_type == "scan.deleted"
        assert event.scan_id == scan.id
        assert event.tenant_id == tenant_id
        assert bus.publish.await_args.kwargs["stream"] == "scan.events"
