"""Unit tests for the Scans domain (F2 Slice 2).

PR0 - persistence contract: the partial unique index that forbids two open
(``pending``) scans sharing a name for the same asset.

Design note: the harness here is deliberately minimal. ``tests/unit/test_assets.py``
carries a heavier alembic harness built for Slice 1's ten-statement migration;
PR0 needs a single ``CREATE UNIQUE INDEX``, so only the pieces this slice
exercises are reproduced. If a third suite needs the same infrastructure,
extract it into a shared helper instead of copying it again.
"""

from __future__ import annotations

import importlib.util
from pathlib import Path
from types import ModuleType

from app.modules.scans.models import Scan

# Name of the index that enforces the business rule: one open definition per
# (tenant_id, asset_id, name). The predicate makes it partial so the name is
# released once the scan leaves ``pending``.
OPEN_NAME_INDEX = "uq_scans_tenant_asset_name_pending"


# The migration that introduces the index is authored later in this work-unit.
# Its revision id is generated by alembic, so it is located by its parent
# instead of by filename.
SLICE_1_HEAD = "e0eafdf389fc"
VERSIONS_DIR = Path(__file__).resolve().parents[2] / "migrations" / "versions"


def _load_slice2_migration() -> ModuleType:
    """Import the Slice 2 migration by locating the revision whose parent is SLICE_1_HEAD."""
    for path in sorted(VERSIONS_DIR.glob("*.py")):
        spec = importlib.util.spec_from_file_location(f"_migration_{path.stem}", path)
        if spec is None or spec.loader is None:  # pragma: no cover - defensive
            continue
        module = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(module)
        if getattr(module, "down_revision", None) == SLICE_1_HEAD:
            return module
    raise AssertionError(
        f"No migration with down_revision={SLICE_1_HEAD!r} found in {VERSIONS_DIR}"
    )


class TestScanOpenNameUniqueIndex:
    """The model must declare the partial unique index, not just the migration."""

    def test_model_declares_the_partial_unique_index(self) -> None:
        indexes = {index.name: index for index in Scan.__table__.indexes}

        assert OPEN_NAME_INDEX in indexes, (
            f"{OPEN_NAME_INDEX} is missing from Scan.__table_args__. "
            "Without it, alembic autogenerate reports drift and alembic check fails."
        )

    def test_index_is_unique_over_tenant_asset_name(self) -> None:
        index = {i.name: i for i in Scan.__table__.indexes}[OPEN_NAME_INDEX]

        assert index.unique is True
        assert [column.name for column in index.columns] == [
            "tenant_id",
            "asset_id",
            "name",
        ]

    def test_index_predicate_is_limited_to_pending(self) -> None:
        index = {i.name: i for i in Scan.__table__.indexes}[OPEN_NAME_INDEX]
        predicate = str(index.dialect_options["postgresql"]["where"])

        assert predicate, "the index must be partial, not a plain unique constraint"
        assert "pending" in predicate
        assert "status" in predicate


class TestOpenNamePreconditionDecision:
    """The precondition decides whether to abort, and explains why in the message."""

    def test_no_duplicates_means_no_abort(self) -> None:
        module = _load_slice2_migration()

        assert module.duplicate_open_name_message([]) is None

    def test_duplicates_produce_an_actionable_message(self) -> None:
        module = _load_slice2_migration()

        message = module.duplicate_open_name_message(
            [("tenant-1", "asset-1", "weekly", 2), ("tenant-2", "asset-2", "nightly", 3)]
        )

        assert message is not None
        assert "weekly" in message
        assert "nightly" in message
        assert "pending" in message
        assert "uq_scans_tenant_asset_name_pending" in message
